#!/usr/bin/env python3
"""
Write Supplement Tables S9 and S11 (LaTeX) from JACS few-shot pairwise statistics CSVs:

  reports/jacs_fewshot/jacs_fewshot_pairwise_stats_aggregate.csv   → Table S9
  reports/jacs_fewshot/jacs_fewshot_pairwise_stats_per_seed.csv → Table S11

Run from the ``project`` directory (``python -m`` loads ``gan_seg`` and needs PyTorch):
  python3 gan_seg/generate_jacs_fewshot_supp_tables.py
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REPORT = ROOT / "reports" / "jacs_fewshot"

COMPARATOR_DISPLAY_S9 = {
    "deeplabv3plus": r"DeepLabV3+",
    "segformer": r"SegFormer",
    "unet": r"UNet",
}


def _fmt_num(x: float, nd: int = 4) -> str:
    return f"{float(x):.{nd}f}"


def _fmt_p_simple(p: float) -> str:
    """Readable p-value for LaTeX (avoid broken scientific formatting)."""
    p = float(p)
    if p < 1e-15:
        return "$<10^{-15}$"
    if p < 1e-12:
        return "$<10^{-12}$"
    if p < 1e-9:
        return "$<10^{-9}$"
    if p < 1e-6:
        return "$<10^{-6}$"
    if p < 1e-3:
        return "$<0.001$"
    if p < 0.01:
        return f"{p:.3f}"
    return f"{p:.4f}"


def table_s9_tex(rows: list[dict]) -> str:
    lines = [
        r"% Generated by gan_seg/generate_jacs_fewshot_supp_tables.py; do not edit by hand.",
        r"\begin{table}[!htbp]",
        r"\centering",
        (
            r"\caption{JACS few-shot external adaptation: aggregate paired differences "
            r"(Hybrid-STEMSeg minus comparator) over RNG seeds $42$, $101$, and $202$. "
            r"Mean paired differences are averaged across seeds; bootstrap 95\% intervals resample seeds with replacement. "
            r"Fisher-combined $p$-values merge per-seed Wilcoxon $p$-values and are \emph{exploratory} "
            r"because seeds use different train/val splits rather than independent cohorts.}"
        ),
        r"\label{tab:sup_jacs_pairwise_aggregate}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{@{}l l r r r r r r@{}}",
        r"\toprule",
        r"$K$ & Comparator & $\overline{\Delta\mathrm{F1}}$ & 95\% CI & $p_{\mathrm{Fish}}^{\mathrm{F1}}$ & $\overline{\Delta\mathrm{IoU}}$ & 95\% CI & $p_{\mathrm{Fish}}^{\mathrm{IoU}}$ \\",
        r"\midrule",
    ]
    for r in sorted(rows, key=lambda x: (int(x["n_shot"]), x["comparator"])):
        k = int(r["n_shot"])
        comp = COMPARATOR_DISPLAY_S9.get(str(r["comparator"]), str(r["comparator"]))
        lines.append(
            f"{k} & {comp} & {_fmt_num(r['f1_mean_of_seed_mean_diffs'])} & "
            f"[{_fmt_num(r['f1_across_seeds_boot95_low'])}, {_fmt_num(r['f1_across_seeds_boot95_high'])}] & "
            f"{_fmt_p_simple(r['f1_fisher_combined_p'])} & "
            f"{_fmt_num(r['iou_mean_of_seed_mean_diffs'])} & "
            f"[{_fmt_num(r['iou_across_seeds_boot95_low'])}, {_fmt_num(r['iou_across_seeds_boot95_high'])}] & "
            f"{_fmt_p_simple(r['iou_fisher_combined_p'])} \\\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


def table_s11_tex(rows: list[dict]) -> str:
    lines = [
        r"% Generated by gan_seg/generate_jacs_fewshot_supp_tables.py; do not edit by hand.",
        r"\begin{table}[!htbp]",
        r"\centering",
        (
            r"\caption{Per-seed paired tests on held-out JACS validation images (same split within each seed). "
            r"$\overline{\Delta}$: mean image-level paired difference (Hybrid-STEMSeg $-$ comparator). "
            r"$p_W$: two-sided Wilcoxon signed-rank test on paired differences. "
            r"Bootstrap 95\% CIs (images) use paired resampling of validation frames within that seed.}"
        ),
        r"\label{tab:sup_jacs_pairwise_per_seed}",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{tabular}{@{}r r l r r r r r r r@{}}",
        r"\toprule",
        r"$K$ & Seed & Comp. & $n_{\mathrm{val}}$ & $\overline{\Delta\mathrm{F1}}$ & $p_W^{\mathrm{F1}}$ & 95\% CI F1 & $\overline{\Delta\mathrm{IoU}}$ & $p_W^{\mathrm{IoU}}$ & 95\% CI IoU \\",
        r"\midrule",
    ]
    for r in sorted(
        rows,
        key=lambda x: (int(x["n_shot"]), int(x["seed"]), x["comparator"]),
    ):
        k = int(r["n_shot"])
        seed = int(r["seed"])
        comp_disp = {"deeplabv3plus": "DL", "unet": "UNet", "segformer": "SegF"}.get(
            str(r["comparator"]), str(r["comparator"])
        )
        n = int(r["n_images_paired"])
        lines.append(
            f"{k} & {seed} & {comp_disp} & {n} & "
            f"{_fmt_num(r['f1_mean_diff_hybrid_minus_comp'])} & "
            f"{_fmt_p_simple(r['f1_wilcoxon_p_two_sided'])} & "
            f"[{_fmt_num(r['f1_boot95_ci_low'])}, {_fmt_num(r['f1_boot95_ci_high'])}] & "
            f"{_fmt_num(r['iou_mean_diff_hybrid_minus_comp'])} & "
            f"{_fmt_p_simple(r['iou_wilcoxon_p_two_sided'])} & "
            f"[{_fmt_num(r['iou_boot95_ci_low'])}, {_fmt_num(r['iou_boot95_ci_high'])}] \\\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\vspace{0.5em}",
            r"\parbox{\linewidth}{\footnotesize DL\,=\,DeepLabV3+, SegF\,=\,SegFormer.}",
            r"\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--report-dir", type=Path, default=DEFAULT_REPORT)
    ap.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Default: same as report-dir",
    )
    cli = ap.parse_args()
    rep = cli.report_dir
    out = cli.out_dir or rep
    out.mkdir(parents=True, exist_ok=True)

    agg_path = rep / "jacs_fewshot_pairwise_stats_aggregate.csv"
    per_path = rep / "jacs_fewshot_pairwise_stats_per_seed.csv"
    if not agg_path.is_file() or not per_path.is_file():
        raise SystemExit(
            f"Missing CSV. Run first:\n"
            f"  python -m gan_seg.jacs_fewshot_pairwise_stats --report-dir {rep}\n"
        )

    with agg_path.open(newline="", encoding="utf-8") as f:
        agg_rows = list(csv.DictReader(f))
    with per_path.open(newline="", encoding="utf-8") as f:
        per_rows = list(csv.DictReader(f))

    # Float conversion
    for row in agg_rows:
        for key in list(row.keys()):
            if key in ("n_shot", "n_seeds", "baseline", "comparator"):
                continue
            row[key] = float(row[key])
    for row in per_rows:
        for key in row:
            if key in ("n_shot", "seed", "baseline", "comparator", "n_images_paired"):
                if key == "n_images_paired":
                    row[key] = int(row[key])
                elif key in ("n_shot", "seed"):
                    row[key] = int(row[key])
                continue
            row[key] = float(row[key])

    s9 = out / "table_s9_jacs_fewshot_aggregate_pairwise.tex"
    s11 = out / "table_s11_jacs_fewshot_per_seed_pairwise.tex"
    s9.write_text(table_s9_tex(agg_rows), encoding="utf-8")
    s11.write_text(table_s11_tex(per_rows), encoding="utf-8")
    print(f"Wrote {s9.resolve()}")
    print(f"Wrote {s11.resolve()}")


if __name__ == "__main__":
    main()
